# Generated by Django 3.2.9 on 2022-10-14 11:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=255, null=True)),
                ('last_config', models.DateField(null=True)),
                ('last_check', models.DateField(null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'UNKNOWN'), (1, 'NOT_INITIALIZED'), (2, 'INITIALIZING'), (3, 'INITIALIZED'), (4, 'RUNNING'), (5, 'HEALTHY'), (6, 'UNHEALTHY'), (7, 'TIMEOUT'), (8, 'ERROR')], default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='systemstatus',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'UNKNOWN'), (1, 'NOT_INITIALIZED'), (2, 'INITIALIZING'), (3, 'INITIALIZED'), (4, 'RUNNING'), (5, 'UPDATING'), (6, 'HEALTHY'), (7, 'UNHEALTHY'), (8, 'TIMEOUT'), (9, 'ERROR')], default=0),
        ),
        migrations.CreateModel(
            name='ServiceStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, default=None, null=True)),
                ('old_status', models.SmallIntegerField(choices=[(0, 'UNKNOWN'), (1, 'NOT_INITIALIZED'), (2, 'INITIALIZING'), (3, 'INITIALIZED'), (4, 'RUNNING'), (5, 'HEALTHY'), (6, 'UNHEALTHY'), (7, 'TIMEOUT'), (8, 'ERROR')], default=0)),
                ('new_status', models.SmallIntegerField(choices=[(0, 'UNKNOWN'), (1, 'NOT_INITIALIZED'), (2, 'INITIALIZING'), (3, 'INITIALIZED'), (4, 'RUNNING'), (5, 'HEALTHY'), (6, 'UNHEALTHY'), (7, 'TIMEOUT'), (8, 'ERROR')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicestatus')),
            ],
        ),
    ]
