# Generated by Django 3.2.9 on 2023-01-13 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tasklog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='parent_task_id',
        ),
        migrations.RemoveField(
            model_name='tasklog',
            name='previous_task_id',
        ),
        migrations.AddField(
            model_name='tasklog',
            name='parent_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent', to='api.tasklog'),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='previous_task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='api.tasklog'),
        ),
    ]
