# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: 
      - created
jobs:
  check:
    runs-on: ubuntu-latest    
    steps: 
      - uses: actions/checkout@v2
      - name: Get version values
        id: vars
        run: |          
          echo ::set-output name=version::$(cat VERSION)                              
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}                
      - name: Show captured versions
        run: |
          echo 'Version in source code: ${{ steps.vars.outputs.version }}'
          echo 'Release version: ${{ steps.vars.outputs.tag }}'                    
      - name: Check version tag
        uses: nick-invision/assert-action@v1.1.0
        if: github.event_name == 'release'
        with:
          expected: ${{ steps.vars.outputs.tag }}
          actual: ${{ steps.vars.outputs.version }}
          comparison: exact
  publish:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps: 
      - uses: actions/checkout@v2
      - name: Store version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
  docker_tag:
    needs: publish
    runs-on: ubuntu-latest
    # if: github.event_name == 'release'
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Store version
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          push: true
          tags: teslace/supervisor:${{ steps.vars.outputs.tag }}, teslace/supervisor:latest
          file: docker/Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
      - name: Login to TeSLA CE Registry
        uses: docker/login-action@v1
        with:
            username: ${{ secrets.TESLA_CE_REGISTRY_USERNAME }}
            password: ${{ secrets.TESLA_CE_REGISTRY_TOKEN }}
            registry: registry.tesla-ce.eu
      - name: Push to TeSLA CE registry
        run: |
          docker pull teslace/supervisor:${{ steps.vars.outputs.tag }}
          docker tag teslace/supervisor:${{ steps.vars.outputs.tag }} registry.tesla-ce.eu/tesla-ce/supervisor:${{ steps.vars.outputs.tag }}
          docker push registry.tesla-ce.eu/tesla-ce/supervisor:${{ steps.vars.outputs.tag }}
          docker tag teslace/supervisor:${{ steps.vars.outputs.tag }} registry.tesla-ce.eu/tesla-ce/supervisor:latest
          docker push registry.tesla-ce.eu/tesla-ce/supervisor:latest
